### ISSUE TITLE
AccountData - accounts and accountBalances are supposed to be arrays but are reduced into objects

### ISSUE THREAD

**Issue by RobinReborn** [ConsenSys-archive/drizzle#4]
I get this warning in react - I have fixed it by modifying AccountData.js and using it locally.

**Comment by adrianmcli** [comment]
This is a bug and it requires 2 realizations:

1. `accounts` should be an array, but it currently isn't.
2. `accountBalances` should be an object, since it is keyed by addresses and that makes perfect sense.

# Problem

1. This [line](https://github.com/trufflesuite/drizzle-suite/blob/develop/packages/store/src/accounts/accountsReducer.js#L9) in the `accountsReducer` uses `Object.assign` instead of an array concatenation (i.e. spread operator) and it forces the array into an object:

   ```js
   return Object.assign({}, state, action.accounts)
   ```

2. This [line](https://github.com/trufflesuite/drizzle-suite/blob/develop/packages/react-components/src/AccountData.js#L68) is expecting an Array of Strings rather than an Object of Strings:

   ```js
   accountBalances: PropTypes.arrayOf(PropTypes.string),
   ```

# Solution
1. This should be:

   ```js
   return [...state, ...action.accounts]
   ```

2. This should be:

   ```js
   accountBalances: PropTypes.objectOf(PropTypes.string),
   ```

**Comment by adrianmcli** [comment]
After some discussion with @cds-amal, we decided to loosen the restraints on the React-Component PropTypes rather than changing the reducer. This is because we don't want to cause any breaking changes without a large version bump.

Therefore, new (temporary) solution is to change from [this](https://github.com/trufflesuite/drizzle-suite/blob/develop/packages/react-components/src/AccountData.js#L67-L68):

```js
accounts: PropTypes.arrayOf(PropTypes.string),
accountBalances: PropTypes.arrayOf(PropTypes.string),
```

to:

```js
accounts: PropTypes.any,
accountBalances: PropTypes.objectOf(PropTypes.string),
```

This will clear up the errors, but we must remember to (for 2.x) implement the solution I listed above.
